### ISSUE TITLE
训练数据集构建问题

### ISSUE THREAD

**Issue by Little-girl-1992** [sakuranew/BERT-AttributeExtraction#1]
请问你的训练数据集是如何构建的啊

**Comment by sakuranew** [comment]
data文件夹里面的数据集是从百科人物词条爬的

**Comment by sakuranew** [comment]
> 请问你的训练数据集是如何构建的啊

我新加 了个描述
https://github.com/sakuranew/BERT-AttributeExtraction#dataset

**Comment by Little-girl-1992** [comment]
> data文件夹里面的数据集是从百科人物词条爬的

你好，请问你数据集里的1和0是如何标注的呢？王永庆#台湾#1 or 0#

王永庆#台湾#1#开的一本早期手抄本长坑王氏族普上就有包括王永庆在内的多名台湾名人的祖籍,并注明何时迁往何地)移居今
王永庆#台湾#1#迁往何地)移居今台北县新店直潭的。王家在台湾第一代祖先是王永庆的曾祖父王天来。王天来是在因灾荒随寡母
王永庆#台湾#1#，王家后来一跃成为当地的有钱人家。如今，王永庆家族是台湾最有名望的大家族，家产丰厚，人丁兴盛。
王永庆#台湾#0#首度跨足电子产业。1986年9月30日，王永庆经13年极力争取后，“六轻计划”获台湾经济主管部门核准通过。1993年，台塑
王永庆#台湾#0#完成了个人资本的原始积累。从那个时候起，王永庆的命运发生了变化。抗日战争胜利后，台湾经济开始发展，建筑业势头最好。王永庆敏
王永庆#台湾#0#王永庆的命运发生了变化。抗日战争胜利后，台湾经济开始发展，建筑业势头最好。王永庆敏锐地发现了这一点，便抓住时机经营木材
王永庆#台湾#0#木材业的商家越来越多，竞争也越来越激烈。王永庆看到这一点，便毅然决定退出木材行业。50年代初，台湾急需发展的几大行业，是纺织、水泥、塑胶
王永庆#台湾#0#家大企业实力状况的调查，台塑集团已经跃居台湾各企业集团的龙头老大。王永庆也以54亿美元的身价登上《福布斯》全球
王永庆#台湾#0#与精神领袖。几十年来，全球化工行业一直把王永庆尊为“经营之神”，其经营之道更是备受推崇，很多台湾企业家都将王永庆的管理经验当作最为实用
王永庆#台湾#0#经营之神”，其经营之道更是备受推崇，很多台湾企业家都将王永庆的管理经验当作最为实用的教科书。有位叫
王永庆#台湾#0#托资金规模逾一百亿元，从事社会慈善事业，台湾内某会计师说，台塑创办人王永庆，打造台塑王国，恐死后遗留庞大财产，被
王永庆#台湾#0#在生前就规划设立公益信托，用来照顾弱势。王永庆在多年前，先砸下六亿元，成立王长庚公益信托，为台湾企业最大宗公益信托案，掀起不少科技界老
王永庆#台湾#0#关企业任职与发展。尽管王家未有人从政，但王永庆长期以来是工商界的龙头，在台湾工商界与社会上具有很高的地位与威望，使
王永庆#台湾#0#良好的政商关系在世界化工行业，台塑董事长王永庆在台湾是一个家喻户晓的传奇式人物。他把台湾塑
王永庆#台湾#0#方唇齿相依，给客户利益自己才能有最大利益王永庆在总结台塑企业的发展过程时说：“如果台湾不是幅员如此狭窄，发展经济深为缺乏资源
王永庆#台湾#0#结束后，以家族集团的形式面世，也将结束自王永庆逝世后，王家始终未出现在富豪榜榜单的尴尬局面。台湾《经济日报》评论文章说，台塑石化打头阵
王永庆#台湾#0#后王永庆时代”的接班布局。台塑集团创办人王永庆去世后，在台湾留下遗产价值逾600亿元（新台币，下同
王永庆#台湾#1#，直至公义获得彰显。”台塑王家可称得上是台湾的豪富之家，其灵魂人物王永庆多次被评为“台湾首富”。他先后娶了三位
王永庆#台湾#1#王家可称得上是台湾的豪富之家，其灵魂人物王永庆多次被评为“台湾首富”。他先后娶了三位太太，大太太是童

**Comment by sakuranew** [comment]
https://github.com/sakuranew/BERT-AttributeExtraction#dataset
先回标，在手工标注核对

**Comment by sakuranew** [comment]
> https://github.com/sakuranew/BERT-AttributeExtraction#dataset
> 先回标，在手工标注核对

会有一部分没有注意到的错误

**Comment by SeekPoint** [comment]
不太理解 0， 1之间的区别
