### ISSUE TITLE
你好，预测时data_dir = a?

### ISSUE THREAD

**Issue by songzeceng** [sakuranew/BERT-AttributeExtraction#10]
根据代码
`predict_examples = processor.get_test_examples(FLAGS.data_dir)`得知训练样例从data_dir里得到，然后根据运行参数`--data_dir=a \`发现data_dir是a.

但项目目录里没有a文件夹啊

**Comment by sakuranew** [comment]
因为没有用到哪个参数。取数据是这里取的
self.train, self.test = self._create_examples(data_process.data_gen, k)
