### ISSUE TITLE
你好，请问这个项目跟知识图谱有什么关系呢

### ISSUE THREAD

**Issue by songzeceng** [sakuranew/BERT-AttributeExtraction#11]
项目名字是“使用基于bert的微调和特征提取方法来进行知识图谱百度百科人物词条属性抽取。”，但我看到里面都是利用bert来进行训练评估和预测，得到准确率召回率这样的指标，好像跟知识图谱没什么关系..

**Comment by sakuranew** [comment]
可以看做属性抽取属于知识图谱
