### ISSUE TITLE
TypeError: 'NoneType' object is not iterable on birthplace dataset, raised on the 2 round

### ISSUE THREAD

**Issue by SeekPoint** [sakuranew/BERT-AttributeExtraction#2]
ub16c9@ub16c9-gpu:~/ub16_prj/BERT-AttributeExtraction/birthplace$ PYTHONPATH=../ python3 run_classifier.py --task_name=my --do_train=true --do_predict=true --data_dir=date/ --vocab_file=../../../data/bert/chinese_L-12_H-768_A-12/vocab.txt --bert_config_file=../../../data/bert/chinese_L-12_H-768_A-12/bert_config.json --init_checkpoint=../../../data/bert/chinese_L-12_H-768_A-12/bert_model.ckpt --max_seq_length=80 --train_batch_size=32 --learning_rate=2e-5 --num_train_epochs=1.0 --output_dir=./output
reading test data ...
8727
962
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f59fc83bc80>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_save_summary_steps': 100, '_eval_distribute': None, '_evaluation_master': '', '_cluster': None, '_experimental_distribute': None, '_protocol': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f59fc4dab70>, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_task_id': 0, '_save_checkpoints_steps': 1000, '_global_id_in_cluster': 0, '_tf_random_seed': None, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_service': None, '_log_step_count_steps': None, '_num_worker_replicas': 1, '_train_distribute': None, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_device_fn': None, '_save_checkpoints_secs': None, '_keep_checkpoint_max': 5, '_model_dir': './output', '_task_type': 'worker', '_keep_checkpoint_every_n_hours': 10000}
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
INFO:tensorflow:Writing example 0 of 8727
INFO:tensorflow:*** Example ***
INFO:tensorflow:guid: 0-0
INFO:tensorflow:tokens: [CLS] 表 大 会 常 务 委 员 会 的 决 定 任 免 驻 外 大 使 ： 任 命 王 雪 峰 为 中 华 人 民 共 和 国 驻 萨 摩 亚 独 立 国 特 命 全 权 大 使 。 [SEP]
INFO:tensorflow:input_ids: 101 6134 1920 833 2382 1218 1999 1447 833 4638 1104 2137 818 1048 7728 1912 1920 886 8038 818 1462 4374 7434 2292 711 704 1290 782 3696 1066 1469 1744 7728 5855 3040 762 4324 4989 1744 4294 1462 1059 3326 1920 886 511 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:label: 0 (id = 0)

INFO:tensorflow:  name = bert/pooler/dense/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*
INFO:tensorflow:  name = bert/pooler/dense/bias:0, shape = (768,), *INIT_FROM_CKPT*
INFO:tensorflow:  name = output_weights:0, shape = (2, 768)
INFO:tensorflow:  name = output_bias:0, shape = (2,)
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
2019-01-02 22:28:29.025812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-02 22:28:29.025856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-02 22:28:29.025874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-02 22:28:29.025880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-02 22:28:29.025991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10080 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./output/model.ckpt-272
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:prediction_loop marked as finished
INFO:tensorflow:prediction_loop marked as finished
k is 2
Traceback (most recent call last):
  File "run_classifier.py", line 850, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 704, in main
    processor = processors[task_name](k)
  File "run_classifier.py", line 195, in __init__
    self.train, self.test = self._create_examples(data_process.data_gen, k)
  File "run_classifier.py", line 218, in _create_examples
    (train_x, test_x), (train_y, test_y) = f(k)
TypeError: 'NoneType' object is not iterable
ub16c9@ub16c9-gpu:~/ub16_prj/BERT-AttributeExtraction/birthplace$

**Comment by sakuranew** [comment]
File "run_classifier.py", line 668
`    for k in range(1, 4):`
“data_process.py“ has 4 methods to process raw data,but I have commented 3 methods and forget to change the k
