### ISSUE TITLE
comparison with relation extraction method by biGRU

### ISSUE THREAD

**Issue by Jiakui** [sakuranew/BERT-AttributeExtraction#4]
https://github.com/crownpku/Information-Extraction-Chinese/tree/master/RE_BGRU_2ATT

这个项目用了 biGRU 的方式做关系提取，您可以跑一下它的数据集，对比一下这个方法和您的方法的准确率的高低吗？

**Comment by sakuranew** [comment]
那个代码我们有用过，在我们自己旧的数据集上F1不如bert，我现在跑跑新的数据集试试

**Comment by sakuranew** [comment]
基本上90%，差了几个百分点
