### ISSUE TITLE
多分类 vs 单分类

### ISSUE THREAD

**Issue by Jiakui** [sakuranew/BERT-AttributeExtraction#5]
对于比较复杂的关系，比如 人和人之间  父母，师生，夫妻，朋友，同事 ，这些不同的关系，是构建一个多分类器  更好， 还是 构建 多个 0-1 分类器更好呢 。。。。。

**Comment by sakuranew** [comment]
多分类效果比较差的。。多个二分类效果会好一点

**Comment by Jiakui** [comment]
怪不得 您这儿  birthdate ， birthplace 搞了不同的文件夹。。。。我刚想着为啥不直接弄个 多分类器。。。。
