### ISSUE TITLE
怎么构建 事件提取 的 分类器？

### ISSUE THREAD

**Issue by Jiakui** [sakuranew/BERT-AttributeExtraction#6]
比如对于 “2018年12月29日,人工智能创业公司北京阿博茨科技有限公司(以下简称“阿博茨科技”)宣布完成3000万美元B轮融资,此轮融资主要投资方为Mindworks概念资本、SIG海纳亚洲、启明创投。“， 这样的一段话，如何构建分类器来提取这个融资事件？

这里面关系包括：“北京阿博茨科技有限公司-融资时间-2018年12月29日”， “北京阿博茨科技有限公司-融资金额-B轮”， “北京阿博茨科技有限公司-融资金额-3000万美元”，“北京阿博茨科技有限公司-投资方-Mindworks概念资本、SIG海纳亚洲、启明创投”。。。。

按照您的建议，也是构建多个关系分类器来一一判断吗？

**Comment by sakuranew** [comment]
事件提取我不太懂，不过要提取出多个关系，一个分类器感觉基本做不到吧或者准确率不高，可以试试多个
