### ISSUE TITLE
4 methods to process raw data

### ISSUE THREAD

**Issue by helenxu** [sakuranew/BERT-AttributeExtraction#7]
File "run_classifier.py", line 668
`    for k in range(1, 4):`
“data_process.py“ has 4 methods to process raw data,but I have commented 3 methods and forget to change the k

_Originally posted by @sakuranew in https://github.com/sakuranew/BERT-AttributeExtraction/issues/2#issuecomment-450881282_

Do you mind explaining the difference among the four methods to process row data? What's the purpose to have four methods? And what's the difference between the strip version and non-strip version? Thank you.

**Comment by sakuranew** [comment]
The four methods to process row data are just try different entity replace strategies（ because different people's names are all person entity but have different embeddings may influence the performance，just have a try）
strip operation is to drop irrelevant parts of sentence

**Comment by helenxu** [comment]
I see. Thank you for the response. I will have a try.

**Comment by sakuranew** [comment]
> I see. Thank you for the response. I will have a try.

I mean I just had a try 😄
