### ISSUE TITLE
请问怎么安装raw_bert呢

### ISSUE THREAD

**Issue by songzeceng** [sakuranew/BERT-AttributeExtraction#9]
我直接用pip install raw_bert发现没有这个库，那么
`from raw_bert import modeling`
`from raw_bert import optimization`
`from raw_bert import tokenization`
这三行里的raw_bert是哪个raw_bert呢

**Comment by sakuranew** [comment]
这些不用安装，只是说是原来的官方bert代码------------------ 原始邮件 ------------------
发件人: "songzeceng"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 下午4:08
收件人: "sakuranew/BERT-AttributeExtraction"<BERT-AttributeExtraction@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [sakuranew/BERT-AttributeExtraction] 请问怎么安装raw_bert呢 (#9)



我直接用pip install raw_bert发现没有这个库，那么
 from raw_bert import modeling
 from raw_bert import optimization
 from raw_bert import tokenization
 这三行里的raw_bert是哪个raw_bert呢
 
&mdash;

**Comment by songzeceng** [comment]
> 这些不用安装，只是说是原来的官方bert代码------------------ 原始邮件 ------------------ 发件人: "songzeceng"<notifications@github.com> 发送时间: 2019年8月22日(星期四) 下午4:08 收件人: "sakuranew/BERT-AttributeExtraction"<BERT-AttributeExtraction@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [sakuranew/BERT-AttributeExtraction] 请问怎么安装raw_bert呢 (#9) 我直接用pip install raw_bert发现没有这个库，那么 from raw_bert import modeling from raw_bert import optimization from raw_bert import tokenization 这三行里的raw_bert是哪个raw_bert呢 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

谢谢，解决了，pip install bert_tensorflow即可
